# These are all the cops that are enabled in the default configuration.

Lint/DuplicateMagicComment: # new in 1.37
  Enabled: true
Style/ArrayIntersect: # new in 1.40
  Enabled: true
Style/ConcatArrayLiterals: # new in 1.41
  Enabled: true
Style/OperatorMethodCall: # new in 1.37
  Enabled: true
Style/RedundantConstantBase: # new in 1.40
  Enabled: true
Style/RedundantDoubleSplatHashBraces: # new in 1.41
  Enabled: true
Style/RedundantEach: # new in 1.38
  Enabled: true
Style/RedundantStringEscape: # new in 1.37
  Enabled: true
Rails/ActionOrder: # new in 2.17
  Enabled: true
Rails/IgnoredColumnsAssignment: # new in 2.17
  Enabled: true
Rails/WhereNotWithMultipleConditions: # new in 2.17
  Enabled: true
RSpec/DuplicatedMetadata: # new in 2.16
  Enabled: true
RSpec/PendingWithoutReason: # new in 2.16
  Enabled: true
RSpec/SortMetadata: # new in 2.14
  Enabled: true
RSpec/Capybara/NegationMatcher: # new in 2.14
  Enabled: true
RSpec/Capybara/SpecificActions: # new in 2.14
  Enabled: true
RSpec/FactoryBot/ConsistentParenthesesStyle: # new in 2.14
  Enabled: true
RSpec/FactoryBot/FactoryNameStyle: # new in 2.16
  Enabled: true
RSpec/Rails/InferredSpecType: # new in 2.14
  Enabled: true